spring:
    config:
        activate:
            on-profile: "test"
    application:
        name: secure
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: ahmed
        password: '1234'
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console: 
            enabled: true


secure:
    config:
        secretkey: eriehiohrweoirhewoirewhrioewrjewoirhewsdbfnfsnfsdjfsndfjsbfsdf
        days: 15


server:
    port: 8080

logging:
    file:
        name: log_test.log   ## Log file



